export default [
  {id: 1, nav: 'home', name: 'Home'},
  {id: 2, nav: 'Gyza', name: 'Gyza'},
  {id: 3, nav: 'Berries', name: 'Berries'},
  {id: 4, nav: 'Ocean', name: 'Ocean'},
  {id: 5, nav: 'LostPlanet', name: 'Lost Planet'},
  {id: 6, nav: 'Flow', name: 'Flow'},
  {id: 7, nav: 'Grid', name: 'Grid'},
  {id: 8, nav: 'Hope', name: 'Hope'},
  {id: 9, nav: 'Tank', name: 'Tank'},
  {id: 10, nav: 'FallsApart', name: 'Falls Apart'},
  {id: 11, nav: 'Physis', name: 'Physis'},
  {id: 12, nav: 'ThreeDMenu', name: '3DMenu'},
  {id: 13, nav: 'Darkness', name: 'Darkness'},
  {id: 14, nav: 'Ice', name: 'Ice'},
];
