export default [
  {id: 1, nav: './', name: 'Home'},
  {id: 2, nav: './Gyza', name: 'Gyza'},
  {id: 3, nav: './Berries', name: 'Berries'},
  {id: 5, nav: './Ocean', name: 'Ocean'},
  {id: 7, nav: './Lost Planet', name: 'Lost Planet'},
  {id: 8, nav: './Flow', name: 'Flow'},
  {id: 9, nav: './Grid', name: 'Grid'},
  {id: 10, nav: './Hope', name: 'Hope'},
  {id: 11, nav: './Tank', name: 'Tank'},
  {id: 12, nav: './FallsApart', name: 'Falls Apart'},
  {id: 13, nav: './Physis', name: 'Physis'},
  {id: 14, nav: './ThreeDMenu', name: '3DMenu'},
  {id: 15, nav: './Darkness', name: 'Darkness'},
  {id: 16, nav: './Ice', name: 'Ice'},
];
